/**
 * Shared adapter types — Track M.1
 */

export interface AdapterPostInput {
  content: string;
  format: 'post' | 'thread' | 'longform' | 'short';
  /** Optional image URL for visual posts (D-5). Generated by /api/og/social. */
  image_url?: string;
  metadata?: Record<string, unknown>;
}

export interface AdapterPostResult {
  ok: boolean;
  // platform-returned id; in shadow mode, prefixed with 'shadow:'
  platform_post_id?: string;
  platform_url?: string;
  error?: string;
  // True if posting was skipped due to missing API keys (stub mode)
  stub?: boolean;
}

export interface PlatformAdapter {
  readonly platform: string;
  /**
   * Post the content. If shadow=true, the adapter MUST NOT call the
   * external platform API — it returns a synthetic shadow result so
   * the caller can log it consistently.
   *
   * If the required API keys are missing, the adapter MUST return
   * { ok: true, stub: true, platform_post_id: 'stub:...' } rather
   * than throwing. This lets the engine be wired and tested even
   * before the chairman gets credentials.
   */
  post(input: AdapterPostInput, shadow: boolean): Promise<AdapterPostResult>;
}

export function shadowResult(platform: string, _content: string): AdapterPostResult {
  void _content;
  const id = `shadow:${platform}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
  return {
    ok: true,
    platform_post_id: id,
    platform_url: `internal://shadow/${platform}`,
    stub: false,
  };
}

export function stubResult(platform: string, _content: string): AdapterPostResult {
  void _content;
  const id = `stub:${platform}:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`;
  return {
    ok: true,
    platform_post_id: id,
    platform_url: `internal://stub/${platform}`,
    stub: true,
  };
}
