import type { VercelRequest, VercelResponse } from '@vercel/node';
import { runDispatch } from '../marketing/lib/dispatcher.js';

export const config = { runtime: 'nodejs', maxDuration: 60 };

/**
 * Marketing Instagram cron (D-7, 2026-04-18).
 *
 * Runs twice daily. Posts 1080x1080 visual cards generated by /api/og/social.
 * Instagram requires an image for every post — the dispatcher should generate
 * a card URL via the og/social endpoint before calling the adapter.
 *
 * Schedule: 0 14,20 * * * (14:00 UTC = 7am PDT, 20:00 UTC = 1pm PDT)
 */
export default async function handler(req: VercelRequest, res: VercelResponse) {
  const baseUrl = `${req.headers['x-forwarded-proto'] ?? 'https'}://${req.headers.host}`;
  const summary = await runDispatch('instagram', baseUrl);
  return res.json(summary);
}
