export type ThemeName = 'dark' | 'light' | 'oled';

export const themes: Record<ThemeName, Record<string, string>> = {
  dark: {
    '--color-bg': '#0a0a0a',
    '--color-surface': '#141414',
    '--color-surface-elevated': '#1a1a1a',
    '--color-surface-sunken': '#0d0d0d',
    '--color-border': '#262626',
    '--color-border-subtle': '#1f1f1f',
    '--color-text': '#fafafa',
    '--color-text-muted': '#a1a1aa',
    '--color-accent': '#3b82f6',
    '--color-positive': '#22c55e',
    '--color-negative': '#ef4444',
    '--font-mono': "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace",
  },
  light: {
    '--color-bg': '#f5f5f5',
    '--color-surface': '#ffffff',
    '--color-surface-elevated': '#ffffff',
    '--color-surface-sunken': '#f0f0f0',
    '--color-border': '#e5e5e5',
    '--color-border-subtle': '#ebebeb',
    '--color-text': '#171717',
    '--color-text-muted': '#737373',
    '--color-accent': '#2563eb',
    '--color-positive': '#16a34a',
    '--color-negative': '#dc2626',
    '--font-mono': "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace",
  },
  oled: {
    '--color-bg': '#000000',
    '--color-surface': '#0a0a0a',
    '--color-surface-elevated': '#111111',
    '--color-surface-sunken': '#050505',
    '--color-border': '#1a1a1a',
    '--color-border-subtle': '#151515',
    '--color-text': '#fafafa',
    '--color-text-muted': '#a1a1aa',
    '--color-accent': '#3b82f6',
    '--color-positive': '#22c55e',
    '--color-negative': '#ef4444',
    '--font-mono': "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace",
  },
};
